use Smash;

--  DO LUT INSERTS

-- CHARACTERS
INSERT INTO characters(id, char_name) VALUES(1,'Bayonetta');
INSERT INTO characters(id, char_name) VALUES(2,'Bowser');
INSERT INTO characters(id, char_name) VALUES(3,'Bowser Jr.');
INSERT INTO characters(id, char_name) VALUES(4,'Captain Falcon');
INSERT INTO characters(id, char_name) VALUES(5,'Charizard');
INSERT INTO characters(id, char_name) VALUES(6,'Chrom');
INSERT INTO characters(id, char_name) VALUES(7,'Cloud');
INSERT INTO characters(id, char_name) VALUES(8,'Corrin');
INSERT INTO characters(id, char_name) VALUES(9,'Daisy');
INSERT INTO characters(id, char_name) VALUES(10,'Dark Pit');
INSERT INTO characters(id, char_name) VALUES(11,'Dark Samus');
INSERT INTO characters(id, char_name) VALUES(12,'Diddy Kong');
INSERT INTO characters(id, char_name) VALUES(13,'Donkey Kong');
INSERT INTO characters(id, char_name) VALUES(14,'Dr. Mario');
INSERT INTO characters(id, char_name) VALUES(15,'Duck Hunt');
INSERT INTO characters(id, char_name) VALUES(16,'Falco');
INSERT INTO characters(id, char_name) VALUES(17,'Fox');
INSERT INTO characters(id, char_name) VALUES(18,'Ganondorf');
INSERT INTO characters(id, char_name) VALUES(19,'Greninja');
INSERT INTO characters(id, char_name) VALUES(20,'Ice Climbers');
INSERT INTO characters(id, char_name) VALUES(21,'Ike');
INSERT INTO characters(id, char_name) VALUES(22,'Incineroar');
INSERT INTO characters(id, char_name) VALUES(23,'Inkling');
INSERT INTO characters(id, char_name) VALUES(24,'Isabelle');
INSERT INTO characters(id, char_name) VALUES(25,'Ivysaur');
INSERT INTO characters(id, char_name) VALUES(26,'Jigglypuff');
INSERT INTO characters(id, char_name) VALUES(27,'Joker');
INSERT INTO characters(id, char_name) VALUES(28,'Ken');
INSERT INTO characters(id, char_name) VALUES(29,'King Dedede');
INSERT INTO characters(id, char_name) VALUES(30,'King K. Rool');
INSERT INTO characters(id, char_name) VALUES(31,'Kirby');
INSERT INTO characters(id, char_name) VALUES(32,'Link');
INSERT INTO characters(id, char_name) VALUES(33,'Little Mac');
INSERT INTO characters(id, char_name) VALUES(34,'Lucario');
INSERT INTO characters(id, char_name) VALUES(35,'Lucas');
INSERT INTO characters(id, char_name) VALUES(36,'Lucina');
INSERT INTO characters(id, char_name) VALUES(37,'Luigi');
INSERT INTO characters(id, char_name) VALUES(38,'Mario');
INSERT INTO characters(id, char_name) VALUES(39,'Marth');
INSERT INTO characters(id, char_name) VALUES(40,'Mega Man');
INSERT INTO characters(id, char_name) VALUES(41,'Meta Knight');
INSERT INTO characters(id, char_name) VALUES(42,'Mewtwo');
INSERT INTO characters(id, char_name) VALUES(43,'Mii Brawler');
INSERT INTO characters(id, char_name) VALUES(44,'Mii Swordfighter');
INSERT INTO characters(id, char_name) VALUES(45,'Mii Gunner');
INSERT INTO characters(id, char_name) VALUES(46,'Mr. Game & Watch');
INSERT INTO characters(id, char_name) VALUES(47,'Ness');
INSERT INTO characters(id, char_name) VALUES(48,'Olimar');
INSERT INTO characters(id, char_name) VALUES(49,'Pac-Man');
INSERT INTO characters(id, char_name) VALUES(50,'Palutena');
INSERT INTO characters(id, char_name) VALUES(51,'Peach');
INSERT INTO characters(id, char_name) VALUES(52,'Pichu');
INSERT INTO characters(id, char_name) VALUES(53,'Pikachu');
INSERT INTO characters(id, char_name) VALUES(54,'Piranha Plant');
INSERT INTO characters(id, char_name) VALUES(55,'Pit');
INSERT INTO characters(id, char_name) VALUES(56,'Richter');
INSERT INTO characters(id, char_name) VALUES(57,'Ridley');
INSERT INTO characters(id, char_name) VALUES(58,'R.O.B.');
INSERT INTO characters(id, char_name) VALUES(59,'Robin');
INSERT INTO characters(id, char_name) VALUES(60,'Rosalina & Luma');
INSERT INTO characters(id, char_name) VALUES(61,'Roy');
INSERT INTO characters(id, char_name) VALUES(62,'Ryu');
INSERT INTO characters(id, char_name) VALUES(63,'Samus');
INSERT INTO characters(id, char_name) VALUES(64,'Sheik');
INSERT INTO characters(id, char_name) VALUES(65,'Shulk');
INSERT INTO characters(id, char_name) VALUES(66,'Simon');
INSERT INTO characters(id, char_name) VALUES(67,'Snake');
INSERT INTO characters(id, char_name) VALUES(68,'Sonic');
INSERT INTO characters(id, char_name) VALUES(69,'Squirtle');
INSERT INTO characters(id, char_name) VALUES(70,'Toon Link');
INSERT INTO characters(id, char_name) VALUES(71,'Villager');
INSERT INTO characters(id, char_name) VALUES(72,'Wario');
INSERT INTO characters(id, char_name) VALUES(73,'Wii Fit Trainer');
INSERT INTO characters(id, char_name) VALUES(74,'Wolf');
INSERT INTO characters(id, char_name) VALUES(75,'Yoshi');
INSERT INTO characters(id, char_name) VALUES(76,'Young Link');
INSERT INTO characters(id, char_name) VALUES(77,'Zelda');
INSERT INTO characters(id, char_name) VALUES(78,'Zero Suit Samus');

-- ITEMS
INSERT INTO items(id, item_name) VALUES(1,'Smash Ball');
INSERT INTO items(id, item_name) VALUES(2,'Assist Trophy');
INSERT INTO items(id, item_name) VALUES(3,'Poké Ball');
INSERT INTO items(id, item_name) VALUES(4,'Master Ball');
INSERT INTO items(id, item_name) VALUES(5,'Dragoon Parts');
INSERT INTO items(id, item_name) VALUES(6,'Daybreak Parts');
INSERT INTO items(id, item_name) VALUES(7,'Bomber');
INSERT INTO items(id, item_name) VALUES(8,'Blast Box');
INSERT INTO items(id, item_name) VALUES(9,'Fake Smash Ball');
INSERT INTO items(id, item_name) VALUES(10,'Sandbag');
INSERT INTO items(id, item_name) VALUES(11,'Food');
INSERT INTO items(id, item_name) VALUES(12,'Maxim Tomato');
INSERT INTO items(id, item_name) VALUES(13,'Heart Container');
INSERT INTO items(id, item_name) VALUES(14,'Fairy Bottle');
INSERT INTO items(id, item_name) VALUES(15,'Healing Sprout');
INSERT INTO items(id, item_name) VALUES(16,'Healing Field');
INSERT INTO items(id, item_name) VALUES(17,'Super Mushroom');
INSERT INTO items(id, item_name) VALUES(18,'Poison Mushroom');
INSERT INTO items(id, item_name) VALUES(19,'Super Star');
INSERT INTO items(id, item_name) VALUES(20,'Warp Star');
INSERT INTO items(id, item_name) VALUES(21,'Metal Box');
INSERT INTO items(id, item_name) VALUES(22,'Bunny Hood');
INSERT INTO items(id, item_name) VALUES(23,'Superspicy Curry');
INSERT INTO items(id, item_name) VALUES(24,'Timer');
INSERT INTO items(id, item_name) VALUES(25,'Lightning');
INSERT INTO items(id, item_name) VALUES(26,'Bullet Bill');
INSERT INTO items(id, item_name) VALUES(27,'Beam Sword');
INSERT INTO items(id, item_name) VALUES(28,'Star Rod');
INSERT INTO items(id, item_name) VALUES(29,'Home-Run Bat');
INSERT INTO items(id, item_name) VALUES(30,'Hammer');
INSERT INTO items(id, item_name) VALUES(31,'Golden Hammer');
INSERT INTO items(id, item_name) VALUES(32,'Lip\'s Stick');
INSERT INTO items(id, item_name) VALUES(33,'Fire Bar');
INSERT INTO items(id, item_name) VALUES(34,'Ore Club');
INSERT INTO items(id, item_name) VALUES(35,'Killing Edge');
INSERT INTO items(id, item_name) VALUES(36,'Death\'s Scythe');
INSERT INTO items(id, item_name) VALUES(37,'Ray Gun');
INSERT INTO items(id, item_name) VALUES(38,'Fire Flower');
INSERT INTO items(id, item_name) VALUES(39,'Super Scope');
INSERT INTO items(id, item_name) VALUES(40,'Gust Bellows');
INSERT INTO items(id, item_name) VALUES(41,'Steel Diver');
INSERT INTO items(id, item_name) VALUES(42,'Drill');
INSERT INTO items(id, item_name) VALUES(43,'Banana Gun');
INSERT INTO items(id, item_name) VALUES(44,'Rage Blaster');
INSERT INTO items(id, item_name) VALUES(45,'Ramblin\' Evil Mushroom');
INSERT INTO items(id, item_name) VALUES(46,'Staff');
INSERT INTO items(id, item_name) VALUES(47,'Bob-omb');
INSERT INTO items(id, item_name) VALUES(48,'Motion-Sensor Bomb');
INSERT INTO items(id, item_name) VALUES(49,'Green Shell');
INSERT INTO items(id, item_name) VALUES(50,'Bumper');
INSERT INTO items(id, item_name) VALUES(51,'Freezie');
INSERT INTO items(id, item_name) VALUES(52,'Mr. Saturn');
INSERT INTO items(id, item_name) VALUES(53,'Gooey Bomb');
INSERT INTO items(id, item_name) VALUES(54,'Smart Bomb');
INSERT INTO items(id, item_name) VALUES(55,'Deku Nut');
INSERT INTO items(id, item_name) VALUES(56,'Smoke Ball');
INSERT INTO items(id, item_name) VALUES(57,'Pitfall');
INSERT INTO items(id, item_name) VALUES(58,'Hothead');
INSERT INTO items(id, item_name) VALUES(59,'Banana Peel');
INSERT INTO items(id, item_name) VALUES(60,'Unira');
INSERT INTO items(id, item_name) VALUES(61,'Soccer Ball');
INSERT INTO items(id, item_name) VALUES(62,'Bombchu');
INSERT INTO items(id, item_name) VALUES(63,'X Bomb');
INSERT INTO items(id, item_name) VALUES(64,'Hocotate Bomb');
INSERT INTO items(id, item_name) VALUES(65,'POW Block');
INSERT INTO items(id, item_name) VALUES(66,'Spiny Shell');
INSERT INTO items(id, item_name) VALUES(67,'Boomerang');
INSERT INTO items(id, item_name) VALUES(68,'Beetle');
INSERT INTO items(id, item_name) VALUES(69,'Cucco');
INSERT INTO items(id, item_name) VALUES(70,'Beehive');
INSERT INTO items(id, item_name) VALUES(71,'Killer Eye');
INSERT INTO items(id, item_name) VALUES(72,'Boss Galaga');
INSERT INTO items(id, item_name) VALUES(73,'Beastball');
INSERT INTO items(id, item_name) VALUES(74,'Black Hole');
INSERT INTO items(id, item_name) VALUES(75,'Franklin Badge');
INSERT INTO items(id, item_name) VALUES(76,'Screw Attack');
INSERT INTO items(id, item_name) VALUES(77,'Back Shield');
INSERT INTO items(id, item_name) VALUES(78,'Super Leaf');
INSERT INTO items(id, item_name) VALUES(79,'Rocket Belt');
INSERT INTO items(id, item_name) VALUES(80,'Super Launch Star');
INSERT INTO items(id, item_name) VALUES(81,'Special Flag');
INSERT INTO items(id, item_name) VALUES(82,'Crate');
INSERT INTO items(id, item_name) VALUES(83,'Rolling Crate');
INSERT INTO items(id, item_name) VALUES(84,'Barrel');
INSERT INTO items(id, item_name) VALUES(85,'Capsule');
INSERT INTO items(id, item_name) VALUES(86,'Party Ball');
INSERT INTO items(id, item_name) VALUES(87,'Grass');

-- STAGES
INSERT INTO stages(id, stage_name) VALUES(1,'3D Land');
INSERT INTO stages(id, stage_name) VALUES(2,'75m');
INSERT INTO stages(id, stage_name) VALUES(3,'Arena Ferox');
INSERT INTO stages(id, stage_name) VALUES(4,'Balloon Fight');
INSERT INTO stages(id, stage_name) VALUES(5,'Battlefield');
INSERT INTO stages(id, stage_name) VALUES(6,'Big Battlefield');
INSERT INTO stages(id, stage_name) VALUES(7,'Big Blue');
INSERT INTO stages(id, stage_name) VALUES(8,'Boxing Ring');
INSERT INTO stages(id, stage_name) VALUES(9,'Bridge of Eldin');
INSERT INTO stages(id, stage_name) VALUES(10,'Brinstar');
INSERT INTO stages(id, stage_name) VALUES(11,'Brinstar Depths');
INSERT INTO stages(id, stage_name) VALUES(12,'Castle Siege');
INSERT INTO stages(id, stage_name) VALUES(13,'Coliseum');
INSERT INTO stages(id, stage_name) VALUES(14,'Corneria');
INSERT INTO stages(id, stage_name) VALUES(15,'Delfino Plaza');
INSERT INTO stages(id, stage_name) VALUES(16,'Distant Planet');
INSERT INTO stages(id, stage_name) VALUES(17,'Dracula\'s Castle');
INSERT INTO stages(id, stage_name) VALUES(18,'Dream Land Super Smash Bros.');
INSERT INTO stages(id, stage_name) VALUES(19,'Dream Land GB');
INSERT INTO stages(id, stage_name) VALUES(20,'Duck Hunt');
INSERT INTO stages(id, stage_name) VALUES(21,'Figure-8 Circuit');
INSERT INTO stages(id, stage_name) VALUES(22,'Final Destination');
INSERT INTO stages(id, stage_name) VALUES(23,'Find Mii');
INSERT INTO stages(id, stage_name) VALUES(24,'Flat Zone ');
INSERT INTO stages(id, stage_name) VALUES(25,'Flat Zone 2');
INSERT INTO stages(id, stage_name) VALUES(26,'Flat Zone X');
INSERT INTO stages(id, stage_name) VALUES(27,'Fountain of Dreams');
INSERT INTO stages(id, stage_name) VALUES(28,'Fourside');
INSERT INTO stages(id, stage_name) VALUES(29,'Frigate Orpheon');
INSERT INTO stages(id, stage_name) VALUES(30,'Gamer');
INSERT INTO stages(id, stage_name) VALUES(31,'Garden of Hope');
INSERT INTO stages(id, stage_name) VALUES(32,'Gaur Plain');
INSERT INTO stages(id, stage_name) VALUES(33,'Gerudo Valley');
INSERT INTO stages(id, stage_name) VALUES(34,'Golden Plains');
INSERT INTO stages(id, stage_name) VALUES(35,'Great Bay');
INSERT INTO stages(id, stage_name) VALUES(36,'The Great Cave Offensive');
INSERT INTO stages(id, stage_name) VALUES(37,'Great Plateau Tower');
INSERT INTO stages(id, stage_name) VALUES(38,'Green Greens');
INSERT INTO stages(id, stage_name) VALUES(39,'Green Hill Zone');
INSERT INTO stages(id, stage_name) VALUES(40,'Halberd');
INSERT INTO stages(id, stage_name) VALUES(41,'Hanenbow');
INSERT INTO stages(id, stage_name) VALUES(42,'Hyrule Castle');
INSERT INTO stages(id, stage_name) VALUES(43,'Icicle Mountain');
INSERT INTO stages(id, stage_name) VALUES(44,'Jungle Hijinxs');
INSERT INTO stages(id, stage_name) VALUES(45,'Jungle Japes');
INSERT INTO stages(id, stage_name) VALUES(46,'Kalos Pokémon League');
INSERT INTO stages(id, stage_name) VALUES(47,'Kongo Falls');
INSERT INTO stages(id, stage_name) VALUES(48,'Kongo Jungle Super Smash Bros.');
INSERT INTO stages(id, stage_name) VALUES(49,'Living Room');
INSERT INTO stages(id, stage_name) VALUES(50,'Luigi\'s Mansion');
INSERT INTO stages(id, stage_name) VALUES(51,'Lylat Cruise');
INSERT INTO stages(id, stage_name) VALUES(52,'Magicant');
INSERT INTO stages(id, stage_name) VALUES(53,'Mario Bros.');
INSERT INTO stages(id, stage_name) VALUES(54,'Mario Circuit Super Smash Bros. for Wii U');
INSERT INTO stages(id, stage_name) VALUES(55,'Mario Galaxy');
INSERT INTO stages(id, stage_name) VALUES(56,'Mementos');
INSERT INTO stages(id, stage_name) VALUES(57,'Midgar');
INSERT INTO stages(id, stage_name) VALUES(58,'Miiverse');
INSERT INTO stages(id, stage_name) VALUES(59,'Moray Towers');
INSERT INTO stages(id, stage_name) VALUES(60,'Mushroom Kingdom Super Smash Bros.');
INSERT INTO stages(id, stage_name) VALUES(61,'Mushroom Kingdom Super Smash Bros. Melee');
INSERT INTO stages(id, stage_name) VALUES(62,'Mushroom Kingdom II');
INSERT INTO stages(id, stage_name) VALUES(63,'Mushroomy Kingdom');
INSERT INTO stages(id, stage_name) VALUES(64,'Mushroom Kingdom U');
INSERT INTO stages(id, stage_name) VALUES(65,'Mute City Super Smash Bros. Melee');
INSERT INTO stages(id, stage_name) VALUES(66,'Mute City SNES');
INSERT INTO stages(id, stage_name) VALUES(67,'New Donk City Hall');
INSERT INTO stages(id, stage_name) VALUES(68,'New Pork City');
INSERT INTO stages(id, stage_name) VALUES(69,'Norfair');
INSERT INTO stages(id, stage_name) VALUES(70,'Onett');
INSERT INTO stages(id, stage_name) VALUES(71,'Orbital Gate Assault');
INSERT INTO stages(id, stage_name) VALUES(72,'Pac-Land');
INSERT INTO stages(id, stage_name) VALUES(73,'Pac-Maze');
INSERT INTO stages(id, stage_name) VALUES(74,'Palutena\'s Temple');
INSERT INTO stages(id, stage_name) VALUES(75,'Paper Mario');
INSERT INTO stages(id, stage_name) VALUES(76,'Peach\'s Castle');
INSERT INTO stages(id, stage_name) VALUES(77,'Princess Peach\'s Castle');
INSERT INTO stages(id, stage_name) VALUES(78,'PictoChat');
INSERT INTO stages(id, stage_name) VALUES(79,'PictoChat 2');
INSERT INTO stages(id, stage_name) VALUES(80,'Pilotwings');
INSERT INTO stages(id, stage_name) VALUES(81,'Pirate Ship');
INSERT INTO stages(id, stage_name) VALUES(82,'Planet Zebes');
INSERT INTO stages(id, stage_name) VALUES(83,'Poké Floats');
INSERT INTO stages(id, stage_name) VALUES(84,'Pokémon Stadium');
INSERT INTO stages(id, stage_name) VALUES(85,'Pokémon Stadium 2');
INSERT INTO stages(id, stage_name) VALUES(86,'Port Town Aero Dive');
INSERT INTO stages(id, stage_name) VALUES(87,'Prism Tower');
INSERT INTO stages(id, stage_name) VALUES(88,'Pyrosphere');
INSERT INTO stages(id, stage_name) VALUES(89,'Rainbow Cruise');
INSERT INTO stages(id, stage_name) VALUES(90,'Rainbow Road');
INSERT INTO stages(id, stage_name) VALUES(91,'Reset Bomb Forest');
INSERT INTO stages(id, stage_name) VALUES(92,'Rumble Falls');
INSERT INTO stages(id, stage_name) VALUES(93,'Saffron City');
INSERT INTO stages(id, stage_name) VALUES(94,'Sector Z');
INSERT INTO stages(id, stage_name) VALUES(95,'Shadow Moses Island');
INSERT INTO stages(id, stage_name) VALUES(96,'Skyloft');
INSERT INTO stages(id, stage_name) VALUES(97,'Skyworld');
INSERT INTO stages(id, stage_name) VALUES(98,'Smashville');
INSERT INTO stages(id, stage_name) VALUES(99,'Spear Pillar');
INSERT INTO stages(id, stage_name) VALUES(100,'Spirit Train');
INSERT INTO stages(id, stage_name) VALUES(101,'Summit');
INSERT INTO stages(id, stage_name) VALUES(102,'Super Happy Tree');
INSERT INTO stages(id, stage_name) VALUES(103,'Super Mario Maker');
INSERT INTO stages(id, stage_name) VALUES(104,'Suzaku Castle');
INSERT INTO stages(id, stage_name) VALUES(105,'Temple');
INSERT INTO stages(id, stage_name) VALUES(106,'Tomodachi Life');
INSERT INTO stages(id, stage_name) VALUES(107,'Tortimer Island');
INSERT INTO stages(id, stage_name) VALUES(108,'Town and City');
INSERT INTO stages(id, stage_name) VALUES(109,'Umbra Clock Tower');
INSERT INTO stages(id, stage_name) VALUES(110,'Unova Pokémon League');
INSERT INTO stages(id, stage_name) VALUES(111,'Venom');
INSERT INTO stages(id, stage_name) VALUES(112,'WarioWare');
INSERT INTO stages(id, stage_name) VALUES(113,'Wii Fit Studio');
INSERT INTO stages(id, stage_name) VALUES(114,'Wily Castle');
INSERT INTO stages(id, stage_name) VALUES(115,'Windy Hill Zone');
INSERT INTO stages(id, stage_name) VALUES(116,'Woolly World');
INSERT INTO stages(id, stage_name) VALUES(117,'Wrecking Crew');
INSERT INTO stages(id, stage_name) VALUES(118,'Wuhu Island');
INSERT INTO stages(id, stage_name) VALUES(119,'Yoshi\'s Island Super Smash Bros. Melee');
INSERT INTO stages(id, stage_name) VALUES(120,'Yoshi\'s Island Super Smash Bros. Brawl');
INSERT INTO stages(id, stage_name) VALUES(121,'Yoshi\'s Story');
